### ISSUE TITLE
Traits can be defined as double arrays

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec-json-schemas#273]
#### Describe the bug

I just noticed that the operation traits https://github.com/asyncapi/spec-json-schemas/blob/master/definitions/2.5.0/operation.json#L13 can be defined with a double array:

```
{
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "http://asyncapi.com/definitions/2.5.0/Reference.json"
          },
          {
            "$ref": "http://asyncapi.com/definitions/2.5.0/operationTrait.json"
          },
          {
            "type": "array",
            "items": [
              {
                "oneOf": [
                  {
                    "$ref": "http://asyncapi.com/definitions/2.5.0/Reference.json"
                  },
                  {
                    "$ref": "http://asyncapi.com/definitions/2.5.0/operationTrait.json"
                  }
                ]
              },
              {
                "type": "object",
                "additionalItems": true
              }
            ]
          }
        ]
      }
    }
```

I don't think this is the intended behavior as it allows you to define traits such as:

```yaml
asyncapi: 2.5.0
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      traits: [[{summary: 'test'}]]
```
