### ISSUE TITLE
Message object allows nested `oneOf`

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec-json-schemas#332]
#### Describe the bug
It is possible to define a message such as:

```
      message:
        oneOf:
          - name: LightMeasured
            payload:
              type: string
          - oneOf: 
            - name: LightMeasured2
              payload:
                type: string
```

and having the schema valid, this should not be the case.

#### How to Reproduce
```
asyncapi: 2.6.0
info:
  title: Streetlights API
  version: 1.0.0
  description: |
    The Smartylighting Streetlights API allows you
    to remotely manage the city lights.
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
servers:
  mosquitto:
    url: 'mqtt://test.mosquitto.org'
    protocol: mqtt
channels:
  light/measured:
    publish:
      summary: >-
        Inform about environmental lighting conditions for a particular
        streetlight.
      operationId: onLightMeasured
      message:
        oneOf:
          - name: LightMeasured
            payload:
              type: string
          - oneOf: 
            - name: LightMeasured2
              payload:
                type: string
```

#### Expected behavior
I was expected the validation of said AsyncAPI file to be invalid instead of valid.
