### ISSUE TITLE
Component messages can contain oneOf

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec-json-schemas#335]
#### Describe the bug
According to the spec, a message in the component section should not be able to be defined with oneOf, but at the moment the following is valid:
```
components:
  messages:
    myMessage:
      oneOf:
        - name: LightMeasured
          payload:
            type: string
```

#### Expected behavior
Expected a validator to mark this as invalid input.
